button:
  - platform: restart
    name: Restart

sensor:
  # Reports the WiFi signal strength/RSSI in dB
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    icon: mdi:wifi-cog
  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    icon: mdi:wifi-cog
  # Up time sensor
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    icon: mdi:alarm-check

# Simple WiFi info
text_sensor:
  - platform: wifi_info
    ip_address:
      name: Device IP Address  
      icon: mdi:wifi-cog
    ssid:
      name: Device Connected SSID
      icon: mdi:wifi-cog
